version: '3'

services:

  postgres:
    container_name: postgres
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: soa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  spacemarine:
    container_name: spacemarine
    build:
      context: spacemarine
      dockerfile: Dockerfile
    restart: no
    ports:
      - "7008:7008"


  starship:
    container_name: starship
    build:
      context: starship
      dockerfile: Dockerfile
    restart: no
    ports:
      - "7010:8080"
      - "8443:8443"
    volumes:
      - wildfly:/opt/jboss/wildfly


volumes:
  postgres_data:
  wildfly:
