spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/soa
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 7008
  servlet:
    context-path: /
    session:
      timeout: 600s
  error:
    include-message: always
  ssl:
    key-store: classpath:keystore/keystore.jks
    key-store-password: password
    enabled: true
